{% set name = "improver" %}
{% set version = "0.21.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/metoppv/improver/archive/{{ version }}.tar.gz
  sha256: ea6de88f41e9347ab94e76e5e5cec28438b0d4a78cd92fd97268469ba2376fc7

build:
  noarch: python
  number: 1
  script: python -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cartopy
    - cftime <1.5
    - cf-units =2.1.5
    - clize
    - dask
    - iris >=3.0,<3.1
    - netCDF4
    - numpy <1.21
    - python-dateutil
    - python-stratify
    - pytz
    - scipy =1.6
    - sigtools
    - sphinx

test:
  requires:
    - pytest
    - mock
    - filelock
  commands:
    - pytest --pyargs improver_tests
  imports:
    - improver

about:
  home: https://github.com/metoppv/improver
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: IMPROVER is a library of algorithms for meteorological post-processing and verification.
  description: IMPROVER is a library of algorithms for meteorological post-processing and verification.
  doc_url: https://improver.readthedocs.io/en/latest/
  dev_url: https://github.com/metoppv/improver

extra:
  recipe-maintainers:
    - benfitzpatrick
    - PaulAbernethy
    - tjtg
    - lucyleeow
