{% set name = "improver" %}
{% set version = "0.19.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/metoppv/improver/archive/{{ version }}.tar.gz
  sha256: aba11541bad6b0226f966269db63d5f9d45f626fbc7ccbd782f3c6bd3cce92ae

build:
  noarch: python
  number: 0
  script: python -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cartopy
    - cftime ==1.0.1
    - cf_units
    - clize
    - dask
    - iris >=2.2, <3.0
    - netCDF4
    - numpy
    - python-dateutil
    - python-stratify
    - pytz
    - scipy >=1.3.0, <1.4.0
    - sigtools
    - sphinx

test:
  imports:
    - improver

about:
  home: https://github.com/metoppv/improver
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: IMPROVER is a library of algorithms for meteorological post-processing and verification.
  description: IMPROVER is a library of algorithms for meteorological post-processing and verification.
  doc_url: https://improver.readthedocs.io/en/latest/
  dev_url: https://github.com/metoppv/improver

extra:
  recipe-maintainers:
    - benfitzpatrick
    - PaulAbernethy
    - tjtg
    - lucyleeow
