{% set name = "improver" %}
{% set version = "1.6.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/metoppv/improver/archive/{{ version }}.tar.gz
  sha256: 19cc8772d30dbcfbad593dece37db5b092e0b24fb2ebbebf03857a3b13fe06b2

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: python -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - cartopy <0.20
    - cftime <1.5
    - cf-units =2.1.5
    - clize
    - dask
    - iris >=3.0,<3.1
    - netCDF4
    - numpy <1.21
    - scipy
    - sigtools
    - sphinx

test:
  commands:
    - improver --help
  imports:
    - improver

about:
  home: https://github.com/metoppv/improver
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: IMPROVER is a library of algorithms for meteorological post-processing and verification.
  description: IMPROVER is a library of algorithms for meteorological post-processing and verification.
  doc_url: https://improver.readthedocs.io/en/latest/
  dev_url: https://github.com/metoppv/improver

extra:
  recipe-maintainers:
    - cpelley
    - benfitzpatrick
    - PaulAbernethy
    - tjtg
    - dmentipl
