{% set name = "improver" %}
{% set version = "1.18.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/metoppv/improver/archive/{{ version }}.tar.gz
  sha256: 7dd6f30add9641f67cadd1ace4fdfdaa9c53cfc671cee806cf007ae9a880e3cc

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: python -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - cartopy
    - clize
    - iris =3.12
    - numpy =2.2
    - scipy =1.15
    - sphinx
    - pandas

test:
  requires:
    - python {{ python_min }}
  commands:
    - improver --help
  imports:
    - improver

about:
  home: https://github.com/metoppv/improver
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: IMPROVER is a library of algorithms for meteorological post-processing and verification.
  description: IMPROVER is a library of algorithms for meteorological post-processing and verification.
  doc_url: https://improver.readthedocs.io/en/latest/
  dev_url: https://github.com/metoppv/improver

extra:
  recipe-maintainers:
    - MoseleyS
    - cpelley
    - PaulAbernethy
    - tjtg
    - dmentipl
