{% set name = "improver" %}
{% set version = "0.18.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/metoppv/improver/archive/v{{ version }}.tar.gz
  sha256: ec0908e10646ef4998125a0d078a217c32489049597602dc463831d7fcc1d9e0

build:
  noarch: python
  number: 1
  script: "python -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cartopy
    - cftime ==1.0.1
    - cf_units
    - clize
    - dask
    - iris >=2.2, <3.0
    - netCDF4
    - numpy
    - python-dateutil
    - python-stratify
    - pytz
    - scipy >=1.3.0, <1.4.0
    - sigtools
    - sphinx

test:
  imports:
    - improver

about:
  home: https://github.com/metoppv/improver
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'IMPROVER is a library of algorithms for meteorological post-processing and verification.'
  description: 'IMPROVER is a library of algorithms for meteorological post-processing and verification.'
  doc_url: https://improver.readthedocs.io/en/latest/
  dev_url: https://github.com/metoppv/improver

extra:
  recipe-maintainers:
    - benfitzpatrick
    - PaulAbernethy
    - tjtg
    - lucyleeow
