{% set name = "improver" %}
{% set version = "1.12.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/metoppv/improver/archive/{{ version }}.tar.gz
  sha256: 4b88db64ad6bafe05f204ed0484d28808c06f446e0ed35d3933b7977b769348d

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: python -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - setuptools
    - cartopy <0.20
    - cftime <1.5
    - cf-units =2.1.5
    - clize
    - dask
    - iris >=3.0,<3.1
    - netCDF4
    - numpy <1.21
    - scipy
    - sigtools
    - sphinx
    - pandas <=2.0.0  # Pinned dependencies of dependencies - https://github.com/metoppv/improver/pull/2011
    - pillow <=10.0.1  # Pinned dependencies of dependencies - https://github.com/metoppv/improver/pull/2011

test:
  requires:
    - python {{ python_min }}
  commands:
    - improver --help
  imports:
    - improver

about:
  home: https://github.com/metoppv/improver
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: IMPROVER is a library of algorithms for meteorological post-processing and verification.
  description: IMPROVER is a library of algorithms for meteorological post-processing and verification.
  doc_url: https://improver.readthedocs.io/en/latest/
  dev_url: https://github.com/metoppv/improver

extra:
  recipe-maintainers:
    - cpelley
    - benfitzpatrick
    - PaulAbernethy
    - tjtg
    - dmentipl
